all:
  children:
    vm:
      hosts:
        node1:
          ansible_host: 127.0.0.1
          ansible_port: 2222
          remote_user: vagrant
        node2:
          ansible_host: 127.0.0.1
          ansible_port: 2200
          remote_user: vagrant


