- name: My play
  hosts: webservers

  tasks:
    - name: Apache config file is updated
      ansible.builtin.copy:
        src: /srv/httpd.j2
        dest: /etc/httpd.conf
      notify:
        - Restart apache

  handlers:
    - name: Restart apache
      ansible.builtin.service:
        name: httpd
        state: restarted