---
- hosts: slaves
  tasks:
    - name: Ensure Python is installed
      apt:
        name: python3
        state: present
    - name: Test command
      command: echo "Hello from {{ inventory_hostname }}"
