---
- hosts: slave1
  become: true
  tasks:
    - name: Test connessione Ansible
      ping:

    - name: Aggiornare pacchetti
      apt:
        update_cache: yes

    - name: Installare Git
      apt:
        name: git
        state: present

    - name: Installare Apache
      apt:
        name: apache2
        state: present

#    - name: Avviare Apache
#      systemd:
#        name: apache2
#        state: reloaded
#        enabled: yes

    - name: Installare MySQL
      apt:
        name: mysql-server
        state: present

#    - name: Avviare MySQL
#      systemd:
#        name: mysql
#        state: started
#        enabled: yes

    - name: Aggiungere repository PHP
      shell: add-apt-repository -y ppa:ondrej/php && apt-get update

    - name: Installare PHP 7.1
      apt:
        name: php7.1
        state: present
