all:
  hosts:
    mailserver.example.com:
      db_backend=db_three.example.com
  children:
    ubuntu:
      children:
        webservers:
          hosts:
            foo.example.com:
              db_backend=db_one.example.com
            bar.example.com:
              db_backend=db_two.example.com
          vars:
            http_port: 80
        dbservers:
          hosts:
            db_one.example.org
            db_two.example.org
            db_three.example.org
