---
- name: Configurare Laravel
  hosts: slave1
  become: true

  vars_files:
    - group_vars/all.yml

  tasks:
    - name: Verifica connessione a MySQL
      shell: mysql -h mysql -u root -p'rootpassword' -e 'SHOW DATABASES;'

    - name: Installa pacchetti indispensabili se non presenti
      become: yes
      apt:
        name:
          - git
          - unzip
          - curl
          - apache2
          - php-cli
          - php-mbstring
          - php-xml
          - php-bcmath
          - php-curl
          - python3-pymysql
        state: present
        update_cache: yes
      tags: install

    - name: Crea database Laravel
      community.mysql.mysql_db:
        name: laravel_db
        state: present
        login_host: mysql
        login_user: root
        login_password: rootpassword

    - name: Crea utente Laravel
      community.mysql.mysql_user:
        name: laravel_user
        password: laravelpass
        priv: 'laravel_db.*:ALL'
        host: '%'
        state: present
        login_host: mysql
        login_user: root
        login_password: rootpassword

    - name: Clonare il repository Laravel
      git:
        repo: "{{ laravel_repo_url }}"
        dest: "{{ laravel_root_dir }}"
        version: master
        force: no
      tags: install

    - name: Download Composer
      script: ./scripts/install_composer.sh

    - name: Spostare eseguibile di Composer
      become: true
      command: "mv composer.phar /usr/local/bin/composer"

    - name: Settaggio permessi Composer
      become: true
      file:
        path: /usr/local/bin/composer
        mode: "a+x"

# SI INCAZZA PERCHE' VUOLE PHP 8.0 E IO GLI HO INSTALLATO PHP 8.3
#    - name: Installare le dipendenze PHP con Composer
#      command: composer install --no-dev --optimize-autoloader
#      args:
#        chdir: "{{ laravel_root_dir }}"
#      tags:
#        - install
#        - update

    - name: Copiare .env.example in .env
      copy:
        src: "{{ laravel_root_dir }}/.env.example"
        dest: "{{ laravel_root_dir }}/.env"
        remote_src: yes
      when: not lookup('ansible.builtin.file', laravel_root_dir + '/.env', errors='ignore')
      tags: install

    - name: Sostituire parametri DB in .env
      lineinfile:
        path: "{{ laravel_root_dir }}/.env"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: '^DB_HOST=.*', line: "DB_HOST={{ db_host }}" }
        - { regexp: '^DB_PORT=.*', line: "DB_PORT={{ db_port }}" }
        - { regexp: '^DB_DATABASE=.*', line: "DB_DATABASE={{ db_database }}" }
        - { regexp: '^DB_USERNAME=.*', line: "DB_USERNAME={{ db_username }}" }
        - { regexp: '^DB_PASSWORD=.*', line: "DB_PASSWORD={{ db_password }}" }
      tags: install

# SI INCAZZA PERCHE' NON HO FATTO IL COMPOSER INSTALL
#    - name: Genera APP_KEY per Laravel
#      command: php artisan key:generate
#      args:
#        chdir: "{{ laravel_root_dir }}"
#      tags: install

# SI INCAZZA PERCHE' NON HO FATTO IL COMPOSER INSTALL
#    - name: Eseguire le migrazioni
#      command: php artisan migrate --force
#      args:
#        chdir: "{{ laravel_root_dir }}"
#      tags:
#        - install
#        - update

    - name: Configurare connessione database in .env
      lineinfile:
        path: "{{ laravel_root_dir }}/.env"
        regexp: '^{{ item.key }}='
        line: "{{ item.key }}={{ item.value }}"
      loop:
        - { key: 'DB_HOST', value: 'mysql' }
        - { key: 'DB_PORT', value: '3306' }
        - { key: 'DB_DATABASE', value: 'laravel_db' }
        - { key: 'DB_USERNAME', value: 'root' }
        - { key: 'DB_PASSWORD', value: 'root' }

    - name: Creare VirtualHost Laravel
      copy:
        dest: /etc/apache2/sites-available/laravel.conf
        content: |
          <VirtualHost *:80>
              ServerAdmin webmaster@localhost
              DocumentRoot {{ laravel_root_dir }}/public

              <Directory {{ laravel_root_dir }}/public>
                  AllowOverride All
                  Require all granted
              </Directory>

              ErrorLog ${APACHE_LOG_DIR}/error.log
              CustomLog ${APACHE_LOG_DIR}/access.log combined
          </VirtualHost>

    - name: Abilitare VirtualHost Laravel
      command: a2ensite laravel.conf

    - name: Abilitare mod_rewrite per Laravel
      command: a2enmod rewrite

    - name: Riavviare Apache
      service:
        name: apache2
        state: restarted