myhosts:

  hosts:
    my_host_01:
      ansible_host: 192.0.2.50
      http_port: 80
    my_host_02:
      ansible_host: 192.0.2.51
      http_port: 443
    my_host_03:
      ansible_host: 192.0.2.52

  vars:
    ansible_user: my_server_user